import json
import logging
from strands import Agent
from strands.models.gemini import GeminiModel
from strands.models.openai import OpenAIModel
from .schemas import CareerPathResponse, CareerMap, NextSteps
from core.settings import (
    GEMINI_API_KEY,
    GEMINI_MODEL_ID,
    OPENAI_API_KEY,
    OPENAI_MODEL_ID,
    LLM_PROVIDER,
)

logger = logging.getLogger(__name__)

gemini_model = GeminiModel(
    client_args={
        "api_key": GEMINI_API_KEY,  # Free api key usage
    },
    # **model_config
    model_id=GEMINI_MODEL_ID,
    params={
        # Model parameters
        "temperature": 0.2,
        "max_output_tokens": 3000,
        "top_p": 0.9,
        "top_k": 40,
    },
)

openai_model = OpenAIModel(
    client_args={
        "api_key": OPENAI_API_KEY,
    },
    # **model_config
    model_id=OPENAI_MODEL_ID,
    params={
        "max_tokens": 3000,
        "temperature": 0.2,
    },
)

if LLM_PROVIDER == "gemini":
    logger.info("Using Gemini model for LLM tasks.")
    selected_model = gemini_model
elif LLM_PROVIDER == "openai":
    logger.info("Using OpenAI model for LLM tasks.")
    selected_model = openai_model
else:
    logger.error(f"Invalid LLM_PROVIDER setting: {LLM_PROVIDER}")
    raise ValueError(f"Invalid LLM_PROVIDER setting: {LLM_PROVIDER}")

# Agent 1: The Analyst
ANALYST_PROMPT = """
You are an elite Staff Engineering Manager and Talent Evaluator powering the 'MiCoach' platform.

Your job is to analyze a user's current role, target role, skills, achievements, and 360 feedback to produce a structured career gap analysis (CareerMap).

You MUST follow these principles:
1. Be direct, objective, and practical. Avoid generic corporate fluff.
2. Base all conclusions strictly on the provided data. 
3. Translate 360 feedback and skill scores into concrete signals (MapNodes).
   - If a skill appears negatively in feedback or has a low score -> prioritize it as a blocker/growth area.
   - If a skill has a high score and positive feedback -> mark it as a strong signal.
4. Do NOT invent new skills. Only use the available steps provided in the user data.
5. The 'fastest_route_message' must clearly answer: "What is holding this person back from their target role?"

CRITICAL TOOL INSTRUCTIONS:
- To provide your answer, you MUST call the `CareerMap` tool.
- Submit the entire nested JSON structure in a single call to `CareerMap`.

Keep all descriptions and insights concise but highly meaningful (2-4 lines max).
"""
analyst_agent = Agent(
    system_prompt=ANALYST_PROMPT,
    model=selected_model,
    structured_output_model=CareerMap,  # Outputs ONLY the map
)

# Agent 2: The Planner
PLANNER_PROMPT = """
You are an expert Career Coach powering the 'MiCoach' platform.

You will receive the user's raw profile data AND a CareerMap generated by an engineering manager. 
Your job is to build a highly actionable, step-by-step roadmap (NextSteps) to get the user to their target role.

You MUST follow these principles:
1. STRICT ROUTING: You MUST select the best activities from the 'available_steps' provided in the raw data. Do not invent completely new training modules if MiCoach already provides them.
2. Actionable & Specific: Actions must be realistic for a real work environment (e.g., "Write a one-page backend design note" instead of "Improve communication").
3. Evidence-Based: Clearly define what 'expected_evidence' looks like so the user knows when they have completed the step.
4. The 'why_now' field must connect the chosen action directly to the blockers or strengths identified in the CareerMap.
5. Identify what 'can_wait': Tell the user what they should explicitly ignore right now to maintain focus.

CRITICAL TOOL INSTRUCTIONS:
- To provide your answer, you MUST call the `NextSteps` tool.
- Submit the entire nested JSON structure in a single call to `NextSteps`.

Your goal is to clearly answer: "Based on the MiCoach available steps, what exactly should this person do next, and how will they prove they did it?"
"""
planner_agent = Agent(
    system_prompt=PLANNER_PROMPT,
    model=selected_model,
    structured_output_model=NextSteps,  # Outputs ONLY the next steps
)


def generate_career_path(validated_data: dict) -> dict:
    """
    Executes a sequential workflow: Analyst -> Planner -> Final Response.
    """
    try:
        # Convert raw input to string
        input_context = json.dumps(validated_data, indent=2, default=str)

        # --- WORKFLOW STEP 1: Generate the Map ---
        logger.info("Starting Agent 1: Analyst")
        prompt_1 = f"User Data:\n\n{input_context}"

        analyst_result = analyst_agent(prompt_1)
        career_map_data: CareerMap = analyst_result.structured_output

        # --- WORKFLOW STEP 2: Generate the Plan ---
        logger.info("Starting Agent 2: Planner")
        # We feed the output of Agent 1 directly into the prompt of Agent 2
        prompt_2 = (
            f"Raw User Data:\n{input_context}\n\n"
            f"Manager's Career Map:\n{career_map_data.model_dump_json(indent=2)}"
        )

        planner_result = planner_agent(prompt_2)
        next_steps_data: NextSteps = planner_result.structured_output

        # --- WORKFLOW STEP 3: Combine and Return ---
        logger.info("Workflow complete. Combining results.")
        final_response = CareerPathResponse(
            career_map=career_map_data, next_steps=next_steps_data
        )

        return final_response.model_dump()

    except Exception as e:
        logger.error(
            f"Failed to generate career path workflow: {str(e)}", exc_info=True
        )
        raise RuntimeError(
            "Failed to analyze career path. Please try again later."
        ) from e
