import json
import logging
from strands import Agent
from strands.models.gemini import GeminiModel
from .schemas import CareerPathResponse, CareerMap, NextSteps
from core.settings import GEMINI_API_KEY, GEMINI_MODEL_ID

logger = logging.getLogger(__name__)

gemini_model = GeminiModel(
    client_args={
        "api_key": GEMINI_API_KEY,
    },
    # **model_config
    model_id=GEMINI_MODEL_ID,
    params={
        # Model parameters
        "temperature": 0.2,
        "max_output_tokens": 3000,
        "top_p": 0.9,
        "top_k": 40,
    },
)


# Agent 1: The Analyst
ANALYST_PROMPT = """
You are an elite Staff Engineering Manager. 
Analyze the provided engineer profile (skills, 360 feedback, achievements).
Your ONLY job is to map out their current state, identify their strongest signals, 
and locate blockers. Generate the CareerMap strictly matching the JSON schema.
"""
analyst_agent = Agent(
    system_prompt=ANALYST_PROMPT,
    model=gemini_model,
    structured_output_model=CareerMap,  # Outputs ONLY the map
)

# Agent 2: The Planner
PLANNER_PROMPT = """
You are an elite Career Coach for Software Engineers.
You will be provided with an engineer's raw profile AND a CareerMap generated by a manager.
Based on these two inputs, select the best activities from the 'available_steps' 
and create a highly actionable roadmap. Generate the NextSteps strictly matching the JSON schema.
"""
planner_agent = Agent(
    system_prompt=PLANNER_PROMPT,
    model=gemini_model,
    structured_output_model=NextSteps,  # Outputs ONLY the next steps
)


def generate_career_path(validated_data: dict) -> dict:
    """
    Executes a sequential workflow: Analyst -> Planner -> Final Response.
    """
    try:
        # Convert raw input to string
        input_context = json.dumps(validated_data, indent=2, default=str)

        # --- WORKFLOW STEP 1: Generate the Map ---
        logger.info("Starting Agent 1: Analyst")
        prompt_1 = f"Profile Data:\n\n{input_context}"

        analyst_result = analyst_agent(prompt_1)
        career_map_data: CareerMap = analyst_result.structured_output

        # --- WORKFLOW STEP 2: Generate the Plan ---
        logger.info("Starting Agent 2: Planner")
        # We feed the output of Agent 1 directly into the prompt of Agent 2
        prompt_2 = (
            f"Raw Profile Data:\n{input_context}\n\n"
            f"Manager's Career Map:\n{career_map_data.model_dump_json(indent=2)}"
        )

        planner_result = planner_agent(prompt_2)
        next_steps_data: NextSteps = planner_result.structured_output

        # --- WORKFLOW STEP 3: Combine and Return ---
        logger.info("Workflow complete. Combining results.")
        final_response = CareerPathResponse(
            career_map=career_map_data, next_steps=next_steps_data
        )

        return final_response.model_dump()

    except Exception as e:
        logger.error(
            f"Failed to generate career path workflow: {str(e)}", exc_info=True
        )
        raise RuntimeError(
            "Failed to analyze career path. Please try again later."
        ) from e
